language:
  - python
matrix:
  include:
  - python: "3.6"
    dist: xenial
  - python: "3.7"
    dist: xenial
install:
  - pip install pipenv
  - make init
script:
  - make test-cli
notifications:
  slack:
    secure: TWUQjb5mMc4iIYy9arFMpda5TsoHnQX3sCFFoGsV+TMTQV9R9Tw0keChdO0Lx1AX5EPby2uuUGN/4U789LIwpuE0bwT36cUc1T/1du5uW1K7IEcQOLHEhJya4aYXD6xTy+6ZGpmTrfqMi8pClSL7b3GnkgnTrQkAn1JItDm5jJCGZiOKifdVZbx+TpjkzGLE0/cM6x8btaSU85HeP8XWxi25EFirc5X6/TT7oGLNEA0indG0JGya4yxgJobND4SiVaCBCdg3voiPYWLfUKMm/5H3b03YSMeK5Jig9dnhAhgso7AuEQPqI4mcvnjyCcXf2E6iU2/H1S/Yo2LlN3pS4F2VTbLvcKInWqfhLhbaRAIAjH8mnR/3aCa58UAnTFgSGahn4zCUpf6nrZ0TBaLiOD65hL2PgoPhPermK+nSF9lSfXFAbtQZSAoGG8QyH8Zsns3nAcd0H3VgWJj3nboE2EV+y/C5l8jxzE6RJtSnnT6RHQ86lNdbyg9YbsdymYSz6EiaSeTZbep3RrPTuIuKOaBOP0gy5D7L31T3fAceYv+jIt3tF9mBo00xE8am8H6diY9FgfY9O3ntXtIplD2WAxJKFEOwQIwc08cTgvRqhxwu1nTRg5n2m5T5LMRAYn1jk0ucziSp38pPdfuJ/BHqP17JYHb20Ghelze0mgHqz38=
