name: "e2e tests"

on:
  push:
    paths:
      - '.github/**/*'
      - 'owcli/**/*'
      - 'tests/**/*'
      - 'Pipfile.lock'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7']
    name: Python ${{ matrix.python }}

    steps:
    - name: Checkout a repository
      uses: actions/checkout@v1
    - name: Install bats
      run: sudo npm install -g bats
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install pipenv
      run: python -m pip install --upgrade pip pipenv
    - name: Change python version to ${{ matrix.python }} in Pipfile
      run: 'sed -ri 's/python_version = ".+"/python_version = "${{ matrix.python }}"/g' Pipfile'
    - name: Install dependencies
      run: pipenv install --dev python
    - name: Test with bats
      run: make test-cli
    - name: Slack notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: "*e2e tests*"
        icon_emoji: "tio2"
        url: ${{ secrets.SLACK_WEBHOOK }}
