name: "e2e tests"

on:
  - push
  - schedule:
    - '*/15 * * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install bats
      run: |
        sudo add-apt-repository ppa:duggan/bats
        sudo apt-get update
        sudo apt-get install bats
    - name: Checkout a repository
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync
    - name: Test with bats
      run: make test-cli
    - name: Slack notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: "*e2e tests*"
        icon_emoji: "tio2"
        channel: "#bot_tadashi-aikawa"
        url: ${{ secrets.SLACK_WEBHOOK }}
