name: "Tests"

on:
  push:
    paths:
      - '.github/**/*'
      - 'owcli/*'
      - 'owcli/**/*'
      - 'tests/*'
      - 'tests/**/*'
      - 'poetry.lock'
      - 'Makefile'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          python -m pip install poetry --pre
          poetry install

      - name: CLI tests
        run: |
          sudo npm install -g bats
          sudo chmod +rx $HOME/.config -R
          make test-cli

      - name: "Slack notification (not success)"
        uses: homoluctus/slatify@master
        if: "! success()"
        with:
          type: ${{ job.status }}
          username: GitHub Actions (Failure)
          job_name: ":python:*${{ matrix.python }}* Tests"
          mention: channel
          mention_if: always
          icon_emoji: "github"
          url: ${{ secrets.SLACK_WEBHOOK }}

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: "Slack Notification (success)"
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          username: GitHub Actions (Success)
          job_name: ":terminal: All tests `OS` :ubuntu:  `Versions` :python: 3.6/3.7/3.8/3.9/3.10/3.11 Succeeded"
          icon_emoji: ":github:"
          url: ${{ secrets.SLACK_WEBHOOK }}

